/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: acfb49e7119b26fdda833cf7ada359a0)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	ALLOWED_ORIGIN: "https://interviews.example.invalid";
	TURN_KEY_ID: "";
	OPERATOR_TOKEN: string;
	TURN_KEY_API_TOKEN: string;
	ROOMS: DurableObjectNamespace<import("./src/index").InterviewRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "InterviewRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGIN" | "TURN_KEY_ID" | "OPERATOR_TOKEN" | "TURN_KEY_API_TOKEN">> {}
}
